# 产出构建产物，方便后续依赖跳过构建步骤
name: release-docker

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get tagname
        id: tagname
        run: echo "value=$(date +'%Y%m%d.%H%M')" >> $GITHUB_OUTPUT
      - name: Build common image
        uses: docker/build-push-action@v6
        with:
          file: docker/build-env.Dockerfile
          context: .
          push: true
          tags: |
            pigeonojdev/clangd-in-browser-build-env:latest
            pigeonojdev/clangd-in-browser-build-env:${{ steps.tagname.outputs.value }}
